### ISSUE TITLE
goctls rpc new 中--module_name参数无效，如下图所示

### ISSUE THREAD

**Issue by franktrue** [suyuan32/simple-admin-example-rpc#2]
![image](https://user-images.githubusercontent.com/10108380/231429217-0ccc9c6b-4b62-43f2-8e49-4611a5e797fe.png)

**Comment by franktrue** [comment]
看了一下昨天的goctls master版本还是好的，应该更新最新master后引起的

**Comment by suyuan32** [comment]
已修复, 变量写错了，module 和 model 看错了，一小时前的更新  @franktrue

**Comment by suyuan32** [comment]
更新下最新代码

**Comment by franktrue** [comment]
可以了，但是有个问题，重新make mac 编译goctls命令后，按照之前的schema和同样的补充，报错如下，不知道是不是你之前说的模版的原因
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/10108380/231441685-88b758b1-9100-401c-8dad-46315062d5c0.png">

**Comment by suyuan32** [comment]
goctls extra ent template -u

**Comment by suyuan32** [comment]
example rpc本身就是无法运行的,里面自带了错误，查看update 文件

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/231442603-c7a05c55-54fb-40b9-8fcd-20a7528f25c8.png)

**Comment by suyuan32** [comment]
把这几个改成set就能运行了

**Comment by suyuan32** [comment]
![image](https://user-images.githubusercontent.com/21239039/231442822-e02e3c62-5a7f-477f-be18-c2b118952573.png)

**Comment by franktrue** [comment]
多谢。还发现个问题就是group和项目名称不能一样，否则会引用重复，导致错误，以及当字段中包含url时转换字段时是全大写，例如我的字段是pic_url 会变为picURL，从而导致一些代码生成上还需要手动再次优化的问题
